[
  {
    symbol: 'LQTYUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'SOLUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'ATOMUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'BTCUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'AAVEUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'LSKUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'MKRUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'GALAUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'GALUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'NTRNUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'OMGUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'NEARUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'MAVUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'MAVIAUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'MASKUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'RENUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'RIFUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'ROSEUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'SKLUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
  {
    symbol: 'TIAUSDT',
    price: 2605.74,
    high: 0,
    low: 0,
    action: 'Price is crossing lower boundary',
    keyLevelName: 'SR-HIHOT',
    isActive: false,
    description: 'Do some shit here. This is flip level.',
    mainImgUrl: 'https://www.tradingview.com/x/mITDOjTo/',
  },
];
